gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of {COLOR GREEN}Pokémon{COLOR DARK_GREY}!\p"
	.string "My name is {COLOR GREEN}Professor Cypress{COLOR DARK_GREY}.\p"
	.string "I'm the {COLOR GREEN}Ryoko{COLOR DARK_GREY} region's Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as {COLOR GREEN}Pokémon{COLOR DARK_GREY}.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "mysteries surrounding Pokémon.\p"
	.string "Personally, I research Ancient\n"
	.string "Pokémon, to find out how\l"
	.string "they came to be.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Now, could you fill out\n"
	.string "this form for me?\p$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a {COLOR BLUE}Male{COLOR DARK_GREY}?\n"
	.string "Or are you a {COLOR RED}Female{COLOR DARK_GREY}?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Great!\n"
	.string "Now, fill out your name.$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Just to verify,\n"
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Perfect!\p"
	.string "That's all the questions\n"
	.string "I have for you.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be stopping by later.\n"
	.string "Come see me in my Pokémon Lab\l"
	.string "in {COLOR GREEN}Myst City{COLOR DARK_GREY}!\p"
	.string "$"
