OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

AlnerwickCity_House1_Object_Woman::
	msgbox AlnerwickCity_House1_Object_Woman_Text_0, MSGBOX_NPC
	end


AlnerwickCity_House1_Object_Woman_Text_0:
	.string "{COLOR GREEN}Alnerwick City{COLOR RED} is my favorite city in all\n"
	.string "of Ryoko.\p"
	.string "It's such a small city that is calming as\n"
	.string "well, not nearly as chaotic as {COLOR GREEN}Myst\l"
	.string "City{COLOR RED}.$"
