EnclavaTown_House_2_MapScripts::
	.byte 0


EnclavaTown_House2_Object_Woman::
	msgbox EnclavaTown_House2_Object_Woman_Text_0, MSGBOX_NPC
	end


EnclavaTown_House2_Object_Woman_Text_0:
	.string "{COLOR RED}Lots of strong trainers go to {COLOR GREEN}Enclava\n"
	.string "Tower{COLOR RED} to train their Pokémon and talk\l"
	.string "to {COLOR GREEN}Master Fijo{COLOR RED}.\p"
	.string "He's the Pokémon Master!$"
