EnclavaTower_MapScripts::
	.byte 0


EnclavaTower_1F_Object_OldWoman::
	msgbox EnclavaTower_1F_Object_OldWoman_Text_0, MSGBOX_NPC
	end


EnclavaTower_1F_Object_OldMan::
	msgbox EnclavaTower_1F_Object_OldMan_Text_0, MSGBOX_NPC
	end


EnclavaTower_1F_Object_OldWoman_Text_0:
	.string "{COLOR RED}This tower has been haunted for years\n"
	.string "now by Ghost-type Pokémon.\p"
	.string "Be careful!\n"
	.string "These ghosts can harm your Pokémon!$"

EnclavaTower_1F_Object_OldMan_Text_0:
	.string "{COLOR BLUE}Ghosts?\n"
	.string "I don't believe in those ghosts!\p"
	.string "Those ghost stories you hear are all\n"
	.string "shams!$"
