FrostpineCity_House_2_MapScripts::
	.byte 0


FrostpineCity_House_2_Object_Woman::
	msgbox FrostpineCity_House_2_Object_Woman_Text_0, MSGBOX_NPC
	end


FrostpineCity_House_2_Object_Man::
	msgbox FrostpineCity_House_2_Object_Man_Text_0, MSGBOX_NPC
	end


FrostpineCity_House_2_Object_Woman_Text_0:
	.string "{COLOR RED}My husband is the one who helped design\n"
	.string "the {COLOR GREEN}Frostpine Pokémon Gym{COLOR RED} puzzle!$"

FrostpineCity_House_2_Object_Man_Text_0:
	.string "{COLOR BLUE}What do I do?\n"
	.string "Why, I'm an engineer!\p"
	.string "I designed the {COLOR GREEN}Frostpine Pokémon Gym{COLOR BLUE}!\p"
	.string "Well, I like to give myself a lot of\n"
	.string "credit for it but it was {COLOR GREEN}Bernie{COLOR BLUE}'s idea!\p"
	.string "He is a real scientist too!$"
